[package]
name = "OpenSMTPD-RS"
version = "0.1.0"
authors = ["FssAy <49795742+DmitrijVC@users.noreply.github.com>"]
edition = "2018"

[dependencies]
serde_json = "1.0.59"
lazy_static = "1.4.0"
hyper = "0.10"
hyper-native-tls = "0.2.1"
ansi_term = "0.12.1"
console = "0.12.0"
chrono = "0.4.19"
